### ISSUE TITLE
请问可以提供一下具体数据集吗

### ISSUE THREAD

**Issue by HANSZJH** [WenjieDu/Awesome_Imputation#1]
谢谢

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. 
If you find our research is helpful to your work, please star⭐️ this repository. Your star is your recognition, 
which can help more people notice PyPOTS and grow PyPOTS community. 
It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by Justin0388** [comment]
实验中用到的几个都是公开的数据集，可以利用PyPOTS中的[TSDB](https://github.com/WenjieDu/TSDB)库进行下载

**Comment by HANSZJH** [comment]
感谢

**Comment by WenjieDu** [comment]
@HANSZJH 如 @Justin0388 描述的那样，这个repo中的代码都是基于PyPOTS ecosystem https://github.com/WenjieDu/PyPOTS 编写的，数据的下载使用的是TSDB，使用方法与预处理请看`data_processing`文件夹下的py脚本 https://github.com/WenjieDu/Awesome_Imputation/blob/main/time_series_imputation_survey_code/data_processing

可以关注一下PyPOTS开源社区

**Comment by HANSZJH** [comment]
感谢，很好的文章和代码实验
